## For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
android.nonTransitiveRClass=true
android.useAndroidX=true
kotlin.code.style=official
org.gradle.jvmargs=-Xmx6144M -Dkotlin.daemon.jvm.options\="-Xmx6144M" -Dfile.encoding\=UTF-8
org.gradle.parallel=true
org.gradle.daemon=true
kotlin.incremental=true
org.gradle.caching=true
org.gradle.tooling.parallel=true
org.gradle.configuration-cache=true