pluginManagement {
    includeBuild("build-logic")
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url = uri("https://jitpack.io") }
    }
}

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

rootProject.name = "MyBrain"
include ':composeApp'
include ':androidApp'
include ':appfunctions'
include ':core:datetime'
include ':tasks:domain'
include ':core:alarm'
include ':notes:domain'
include ':core:preferences'
include ':core:storage'
include ':core:di'
include ':core:widget'
include ':calendar:domain'
include ':diary:domain'
include ':bookmarks:domain'
include ':core:ui'
include ':widget'
include ':settings:domain'
include ':core:database'
include ':tasks:presentation'
include ':notes:data'
include ':tasks:data'
include ':notes:presentation'
include ':diary:presentation'
include ':bookmarks:presentation'
include ':calendar:presentation'
include ':settings:presentation'
include ':settings:data'
include ':diary:data'
include ':calendar:data'
include ':bookmarks:data'
include ':ai:presentation'
include ':ai:domain'
include ':ai:data'
include ':local-sync'
