package com.mhss.app.preferences

object PrefsConstants {

    const val SETTINGS_PREFERENCES = "settings_preferences"
    const val SETTINGS_THEME_KEY = "settings_theme"
    const val SETTINGS_MATERIAL_YOU = "material_you"
    const val DEFAULT_START_UP_SCREEN_KEY = "default_start_up_screen"
    const val SHOW_COMPLETED_TASKS_KEY = "show_completed_tasks"
    const val SHOW_ALL_NOTES_KEY = "show_all_notes"
    const val TASKS_ORDER_KEY = "tasks_order"
    const val NOTE_VIEW_KEY = "note_view"
    const val BOOKMARK_VIEW_KEY = "bookmark_view"
    const val NOTES_ORDER_KEY = "notes_order"
    const val BOOKMARK_ORDER_KEY = "bookmark_order"
    const val DIARY_ORDER_KEY = "diary_order"
    const val EXCLUDED_CALENDARS_KEY = "excluded_calendars"
    const val CALENDAR_VIEW_MODE_KEY = "calendar_view_mode"
    const val FIRST_DAY_OF_WEEK_KEY = "first_day_of_week"
    const val APP_FONT_KEY = "app_font"
    const val BLOCK_SCREENSHOTS_KEY = "block_screen_shots"
    const val LOCK_APP_KEY = "lock_app"
    const val FONT_SIZE_KEY = "font_size"

    const val OPENAI_URL_KEY = "openai_url"
    const val OPENAI_USE_URL_KEY = "openai_use_url"
    const val OPENAI_MODEL_KEY = "openai_model"
    const val OPENAI_KEY = "openai_key"
    const val ANTHROPIC_MODEL_KEY = "anthropic_model"
    const val ANTHROPIC_KEY = "anthropic_key"
    const val OPEN_ROUTER_MODEL_KEY = "open_router_model"
    const val OPEN_ROUTER_KEY = "open_router_key"
    const val REQUESTY_MODEL_KEY = "requesty_model"
    const val REQUESTY_KEY = "requesty_key"

    const val LM_STUDIO_MODEL_KEY = "lm_studio_model"
    const val LM_STUDIO_URL_KEY = "lm_studio_url"
    const val OLLAMA_MODEL_KEY = "ollama_model"
    const val OLLAMA_URL_KEY = "ollama_url"
    const val GEMINI_MODEL_KEY = "gemini_model"
    const val GEMINI_KEY = "gemini_key"
    const val AI_PROVIDER_KEY = "ai_api"
    const val AI_TOOLS_ENABLED_KEY = "ai_tools_enabled"

    const val EXTERNAL_NOTES_ENABLED = "external_notes_enabled"
    const val EXTERNAL_NOTES_FOLDER_URI = "markdown_note_folder_uri"
    const val EXTERNAL_NOTES_FOLDER_PATH = "markdown_note_folder_path"

    const val AUTO_BACKUP_ENABLED = "auto_backup_enabled"
    const val AUTO_BACKUP_FOLDER_URI = "auto_backup_folder_uri"
    const val AUTO_BACKUP_FREQUENCY = "auto_backup_frequency"
    const val AUTO_BACKUP_FREQUENCY_AMOUNT = "auto_backup_frequency_amount"
}